# -*- coding: utf-8 -*-
"""Text _to_image_generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c1vsP1gOZHhmfhrdxZj7Q-vTcbIf5CEN

# 1-Install all the required package
"""

!pip install --upgrade diffusers transformers -q# your image generator to use pretrained model

!pip install diffusers

# import necessory libraries
from pathlib import Path
import tqdm
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import cv2
from diffusers import StableDiffusionPipeline
from transformers import pipeline, set_seed

# use pretrained model
class CFG:
    device = "cuda" if torch.cuda.is_available() else "cpu"  # Check if CUDA is available
    seed = 42
    torch.manual_seed(seed)  # Set seed for CPU operations
    if device == "cuda":
        torch.cuda.manual_seed(seed)  # Set seed for CUDA operations
    generator = torch.Generator(device=device).manual_seed(seed)
    image_gen_steps = 35
    image_gen_model_id = "stabilityai/stable-diffusion-2"
    image_gen_size = (400, 400)
    image_gen_guidance_scale = 9
    prompt_gen_model_id = 'gpt-2'
    prompt_dataset_size = 6
    prompt_max_length = 12

image_gen_model=StableDiffusionPipeline.from_pretrained(
    CFG.image_gen_model_id,torch_dtype=torch.float16,
    revision='fp16',
    use_auth_token="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",
    guidance_scale=9
)
image_gen_model=image_gen_model.to(CFG.device)

def generate_image(prompt, model):
  image=model(
      prompt, num_inference_steps=CFG.image_gen_steps,
      generator=CFG.generator,
      guidance_scale=CFG.image_gen_guidance_scale,
  ).images[0]
  image=image.resize(CFG.image_gen_size)
  return image

generate_image("two trains crossing each other", image_gen_model)

generate_image('Two boy playing football', image_gen_model)

generate_image("Crossing river between two mountains", image_gen_model)

generate_image("Flying birds in the sky", image_gen_model)

generate_image("Give me a photo of bollywood actor salman khan", image_gen_model)

generate_image("Give me a photo of Dr APJ Abdul kalam", image_gen_model)